CREATE TABLE friends (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  user_id_1 INT(11) NOT NULL ,
  user_id_2 INT(11) NOT NULL ,
  statues   SMALLINT(1) NOT NULL ,
  request_from INT(11) NOT NULL ,
  created_at DATETIME,
  updated_at DATETIME,
  FOREIGN KEY (user_id_1) REFERENCES users(id) ON UPDATE CASCADE ON DELETE NO ACTION,
  FOREIGN KEY (user_id_2) REFERENCES users(id) ON UPDATE CASCADE ON DELETE NO ACTION,
  FOREIGN KEY (request_from) REFERENCES users(id) ON UPDATE CASCADE ON DELETE NO ACTION
);